from http.server import BaseHTTPRequestHandler, HTTPServer

class OnlinePharmacy(BaseHTTPRequestHandler):


    def make_content(self):
        return( "<html>"
                "<head>"
                "<title>F~OnlinePharmacy</title>"
                "</head>"
                "<meta name='viewport' content='width=device-width, initial-scale=1'>"
                "<style>"
                "{box-sizing: broader-box}"
                "body {font-family: 'Georgia', sans-serif;}"
                ".tab {float: left; border 1px solid ##9999ff; background-color: #9999ff; width: 20%; height:100%}"
                ".tab button {display: block; background-color: #9999ff; color: white; padding: 22px 16px; width:100%; border: none; outline: none; text-align: left; cursor: pointer; transition: 0.3s; font-size: 25px;}"
                ".tab button:hover {background-color: #ccffcc;}"
                ".tab button.active {background-color: #ccffcc}"
                ".tabcontent {float: left; padding: 0px 12px; border: 1xp solid ##9999ff; width: 70%; border-left: none; height: 300px;} "
                "</style>"
                "</head>"
                "<body>"
                "<div class='tab'>"
                    "<button class = 'tablinks' onclick='illness(event, 'Allergies')' id ='defultOpen'>Allergies</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Asthma')' id ='defultOpen'>Asthma</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Cold & Flu')' id ='defultOpen'>Cold & Flu</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Cough & Phlegm')' id ='defultOpen'>Cough & Phlegm</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Dry eyes')' id ='defultOpen'>Dry eyes</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Ear infection')' id ='defultOpen'>Ear infection</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Headache')' id ='defultOpen'>Headache</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Heartburn')' id ='defultOpen'>Heartburn</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'High fever')' id ='defultOpen'>High fever</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Joint sprain')' id ='defultOpen'>Joint sprain</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Minor muscle/joint pain')' id ='defultOpen'>Minor muscle/joint pain</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Pink eye')' id ='defultOpen'>Pink eye</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Pregnancy Vitamin-B')' id ='defultOpen'>Pregnancy Vitamin-B</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Runny nose')' id ='defultOpen'>Runny nose</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Teething')' id ='defultOpen'>Teething</button>"
                    "<button class = 'tablinks' onclick='illness(event, 'Toothache')' id ='defultOpen'>Toothache</button>"
                "</div>"
                "<div id='Allergies' class='tabcontent'>"
                    "<h2>Allergies</h2>"
                    "<p>An allergy is a chronic condition involving an abnormal reaction to an ordinarily harmless substance called an allergen. Allergens can include aeroallergens such as dust mite, mold, and tree weed and grass pollen, as well as food allergens such as milk, egg, soy, wheat, nut or fish proteins.</p>"
                    "<h3>ZYRTEC</h3>"
                    "<p>Zyrtec is a good medicine to overcome allergic reactions. Read the following paragraph regarding the dozage and you will certainly feel better once you start your medication.</p>"
                    "<h3>Dosage</h3>"
                    "<p>2 - 6y rs: drink 2.5ml a day.</p>"
                    "<p>7 - 64 yrs: drink around 5-10ml a day depending on severity.</p>"
                    "<p>65 + yrs: drink 5ml a day.</p>"
                "</div>"
                "<div id='Asthma' class='tabcontent'>"
                    "<h2>Asthma</h2>"
                    "<p>Asthma is a condition in which your airways narrow and swell and may produce extra mucus. This can make breathing difficult and trigger coughing, a whistling sound (wheezing) when you breathe out and shortness of breath. For some people, asthma is a minor nuisance.</p>"
                    "<h3>VENTOLIN</h3>"
                    "<p>Ventolin is a product in which a person with asthma inhilates from the opening. The Ventolin is used to overcome coughing and wheezing</p>"
                    "<h3>Dosage</h3>"
                    "<p>1 + yrs: 1-2 inhilations whenever needed</p>"
                "</div>"
                "<div id='Cold & Flue' class='tabcontent'>"
                    "<h2>Cold & Flu</h2>"
                    "<p>Flu and the common cold are both respiratory illnesses but they are caused by different viruses. Because these two types of illnesses have similar symptoms, it can be difficult to tell the difference between them based on symptoms alone. In general, flu is worse than the common cold, and symptoms are more intense. Colds are usually milder than flu. People with colds are more likely to have a runny or stuffy nose. Colds generally do not result in serious health problems, such as pneumonia, bacterial infections, or hospitalizations. Flu can have very serious associated complications.</p>"
                    "<h3>BRUFEN</h3>"
                    "<p>Brufen is recomended by many doctors proven its effects in overcoming the powers of both the cold and the flu.</p>"
                    "<h3>Dosage</h3>"
                    "<p>1 - 2 yrs: drink 2.5ml three times a day</p>"
                    "<p>3 - 7 yrs: drink 5ml three times a day</p>"
                    "<p>8 - 12 yrs: drink 10 ml three times a day</p>"
                    "<h3>FLUDREX</h3>"
                    "<p>Fludrex is in a form of a tablet that is needed to be swollowed along with some water to make it easier to make its ways down to the stomach. Fludrex is good at releiving cold & flu symptoms.</p>"
                    "<h3>Dosgae</h3>"
                    "<p>13 + yrs: swollow 1-2 tablets at a time, no more than 8 tablets a day</p>"
                "</div>"
                "<div id='Cough & Phlegm' class='tabcontent'>"
                    "<h2>Cough & Phlegm</h2>"
                    "<p>A cough is a reflex action to clear your airways of mucus and irritants such as dust or smoke. It's rarely a sign of anything serious. A 'dry cough' means it's tickly and doesn't produce any phlegm (thick mucus). A 'chesty cough' means phlegm is produced to help clear your airways.</p>"
                    "<h3>PROSPAN</h3>"
                    "<p>Prospan by Helixia Cough Syrup. Prospan by Helixia is a naturally-sourced, over-the-counter cough syrup that is clinically proven to relieve coughs, loosen mucus & phlegm and alleviate the symptoms of chronic bronchitis.</p>"
                    "<h3>Dosage</h3>"
                    "<p>0 - 6 yrs: drink 2.5ml twice a day</p>"
                    "<p>7 - 12 yrs:  drink 5ml twice a day</p>"
                    "<p>12 + yrs: drink 5ml three times a day</p>"
                "</div>"
                "<div id='Dry eyes' class='tabcontent'>"
                    "<h2>Dry eyes</h2>"
                    "<p>Our eyes need tears to stay healthy and comfortable. If your eyes do not produce enough tears, it is called dry eye. Dry eye is also when your eyes do not make the right type of tears or tear film.</p>"
                    "<h3>Refresh Tears</h3>"
                    "<p>is an instantly moisturizes to provide immediate, soothing relief for dry, irritated eyes. It has many of the same healthy qualities as your own natural tears. Refresh Tears is an artificial tear that comes in a convenient multi-dose bottle and is safe to use as often as needed.</p>"
                    "<h3>Dosage</h3>"
                    "<p>10 + yrs: allow 1-2 eyedrops into your eye when needed</p>"
                "</div>"
                "<div id='Ear infection' class='tabcontent'>"
                    "<h2>Ear infection</h2>"
                    "<p>Acute middle ear infection, medically called acute otitis media is inflammation of the middle ear.</p>"
                    "<h3>APIGEN</h3>"
                    "<p>Apigen is used for the treatment of bacterial eye infections affecting eyelids, conjunctiva and cornea. For the prevention of eye infection after the removal of a foreign body. For the treatment of external ear bacterial infections (Otitis Externa). Effective against stubborn bacteria, such as: pseudomonas Aeruginosa.</p>"
                    "<h3>Dosage</h3>"
                    "<p>2 + yrs: allow 1-2 drops into the infected ear twice a day</p>"
                    "</div>"


                "<script>"
                "function illness(evt, Name) {var i, tabcontent, tablinks; tabcontent = document.getElementsByClassName('tabcontent'); for (i=0; i < tabcontent.length; i++){tabcontent[i].style.display='none'}"
                "tablinks = document.getElementByClassName('tablinks'); for(i = 0; i < tablinks.length; i++) {tablinks[i].className = tablinks[i].className.replace('active', '');}"
                "document.getElementById(Name).style.display='block'; evt.currentTarget.className += 'active';}"
                "document.getElementById('defultOpen').click();"
                "</script>"
                "</body>"
                "</html>" )

    def do_GET(self):
        page_html = self.make_content()
        self.send_response(200)
        self.send_header("content-type", "text/html")
        self.end_headers()
        self.wfile.write(page_html.encode())

myServer = HTTPServer(('0.0.0.0', 9011), OnlinePharmacy)
myServer.serve_forever()